{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "<% platform %>-<% service %>-test.serviceAccountName" . }}
  labels: {{- include "<% platform %>-<% service %>-test.labels" . | nindent 4 }}
  annotations: {{- include "<% platform %>-<% service %>-test.annotations" . | nindent 4 }}
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
