# service tree labels
landscape: test
platform: <% platform %>
service: <% service %>

# tilt port
port: <% port.test %>

# "local" or "cluster"
type: local

# fast mode
# 1. does not start the cluster, automatically assumes that your cluster already created
# 2. does not clean up resources. This makes your future starts faster
fast: false

# whether to start local cluster. If false, will connect to current context
startCluster: true
