# yaml-language-server: $schema=./schema.json
$schema: ./schema.json
app:
  landscape: local-prod
databases:
  main:
    dev:
      autoMigrate: false
      autoSeed: false
    migration:
      migrate: true
      seed: true
  comment:
    dev:
      autoMigrate: false
      autoSeed: false
    migration:
      migrate: true
      seed: true
caches:
  main:
    dev:
      autoSeed: false
    migration:
      autoSeed: true

storages: {}
