apiVersion: v1
kind: Pod
metadata:
  name: test-result-extractor
spec:
  containers:
    - name: test-result-extractor
      image: alpine:3.18
      command:
        - ash
        - -c
        - sleep infinity
      volumeMounts:
        - name: test-storage
          mountPath: /app/test-results
  volumes:
    - name: test-storage
      persistentVolumeClaim:
        claimName: test-result-volume
