apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-result-volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  hostPath:
    path: "/mnt/test-result"
