apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-result-volume
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  volumeName: test-result-volume
