apiVersion: v1
kind: Service
metadata:
  name: {{ include "gotrade-nestjs-api.fullname" . }}
  labels: {{- include "gotrade-nestjs-api.labels" . | nindent 4 }}
  annotations: {{- include "gotrade-nestjs-api.annotations" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "gotrade-nestjs-api.selectorLabels" . | nindent 4 }}
