{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gotrade-nestjs-api.serviceAccountName" . }}
  labels: {{- include "gotrade-nestjs-api.labels" . | nindent 4 }}
  annotations: {{- include "gotrade-nestjs-api.annotations" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
