{{- if .Values.secret.fake.enable }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels: {{- include "gotrade-nestjs-root.labels" . | nindent 4 }}
  annotations: {{- include "gotrade-nestjs-root.annotations" . | nindent 4 }}
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-4"
type: Opaque
data:
  {{- range $line := .Files.Lines .Values.secret.fake.path }}
  {{- $parts := splitList "=" $line }}
  {{- if eq (len $parts) 2 }}
  {{ index $parts 0 }}: {{ index $parts 1 | b64enc | quote }}
  {{- end }}
  {{- end }}


{{- end }}
