apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "<% platform %>-<% service %>-migration.fullname-with-suffix" (dict "arg" "config" "root" .) }}
  labels: {{- include "<% platform %>-<% service %>-migration.labels" . | nindent 4 }}
  annotations: {{- include "<% platform %>-<% service %>-migration.labels" . | nindent 4 }}
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
data:
  {{ .Values.serviceTree.landscape }}.config.yaml: |
    {{- $path := printf "%s%s.config.yaml" "app/" .Values.serviceTree.landscape -}}
    {{- $fileContent := .Files.Get $path -}}
    {{- $config := fromYaml $fileContent -}}
    {{- $final := merge $config .Values.config -}}
    {{- toYaml $final | nindent 4 }}

