apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gotrade-nestjs-test.fullname-with-suffix" (dict "arg" "config" "root" .) }}
  labels: {{- include "gotrade-nestjs-test.labels" . | nindent 4 }}
  annotations: {{- include "gotrade-nestjs-test.labels" . | nindent 4 }}
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
data:
  {{ .Values.serviceTree.landscape }}.config.yaml: |
    {{- $path := printf "%s%s.config.yaml" "app/" .Values.serviceTree.landscape -}}
    {{- $fileContent := .Files.Get $path -}}
    {{- $config := fromYaml $fileContent -}}
    {{- $final := merge .Values.config $config -}}
    {{- toYaml $final | nindent 4 }}

