apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "gotrade-nestjs-test.fullname" . }}
  annotations: {{- include "gotrade-nestjs-test.annotations" . | nindent 4 }}
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
  labels: {{- include "gotrade-nestjs-test.labels" . | nindent 4 }}
    tr8.io/type: job
spec:
  template:
    metadata:
      name: {{ include "gotrade-nestjs-test.fullname" . }}-migration
      labels: {{- include "gotrade-nestjs-test.labels" . | nindent 8 }}
        tr8.io/type: job
      annotations: {{- include "gotrade-nestjs-test.annotations" . | nindent 8 }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          command:
            {{- toYaml .Values.command | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: LANDSCAPE
              value: {{ .Values.serviceTree.landscape }}
          {{- if.Values.envFromSecret }}
          envFrom:
            - secretRef:
                name: {{ .Values.envFromSecret }}
          {{- end }}
          volumeMounts:
          {{- if .Values.mountConfig }}
            - mountPath: /app/dist/config/app/{{ .Values.serviceTree.landscape }}.config.yaml
              name: config-volume
              subPath: {{ .Values.serviceTree.landscape }}.config.yaml
          {{- end }}
          {{- if .Values.volume.enable }}
            - mountPath: /app/test-results
              name: test-result-storage
          {{- end }}
      volumes:
      {{- if .Values.mountConfig }}
        - name: config-volume
          configMap:
            name: {{ include "gotrade-nestjs-test.fullname-with-suffix" (dict "arg" "config" "root" .) }}
            items:
              - key: {{ .Values.serviceTree.landscape }}.config.yaml
                path: {{ .Values.serviceTree.landscape }}.config.yaml
      {{- end }}
      {{- if .Values.volume.enable }}
        - name: test-result-storage
          persistentVolumeClaim:
            claimName: {{ .Values.volume.name }}
      {{- end }}
      restartPolicy: Never


      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "gotrade-nestjs-test.serviceAccountName" . }}
  backoffLimit: 4
