{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "<% platform %>-<% service %>-api.serviceAccountName" . }}
  labels: {{- include "<% platform %>-<% service %>-api.labels" . | nindent 4 }}
  annotations: {{- include "<% platform %>-<% service %>-api.annotations" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
