# yaml-language-server: $schema=./schema.json
$schema: ./schema.json
mode: app
host:
  port: 3000
  host: '::'
otel:
  logging:
    enableAutoAPILogging: true
    level: info
    prettify: false
  metrics:
    api:
      enable: true
      defaultAttributes: {}
      ignoreRoutes: []
      ignoreUndefinedRoutes: false
    exporter:
      interval: 1000
      use: otlp
      otlp:
        compression: gzip
        url: http://otel-otlp-collector.otel.svc:4318
        timeout: 30000
    hostMetrics: false
  trace:
    exporter:
      use: otlp
      otlp:
        compression: gzip
        url: http://otel-otlp-collector.otel.svc:4318
        timeout: 30000
app:
  landscape: staging
  swagger:
    title: Staging Gotrade NestJS API
    description: NestJS API is a template API for Gotraders to create microservices
    version: '1.0'
databases:
  main:
    dev:
      autoMigrate: false
      autoSeed: false
    migration:
      migrate: true
      seed: true
      timeout: 30
    driverOptions:
      connection:
        ssl: true
  comment:
    dev:
      autoMigrate: false
      autoSeed: false
    migration:
      migrate: true
      seed: true
      timeout: 30
    driverOptions:
      connection:
        ssl:
          rejectUnauthorized: true
caches:
  main:
    dev:
      autoSeed: false
    migration:
      autoSeed: true
    connection:
      tls: true
storages:
  main:
    dev:
      autoMigrate: false
      autoSeed: false
    migration:
      autoSeed: true
      autoMigrate: true
    connection:
      port: 443
      useSSL: true
      endpoint: s3.amazonaws.com
